
#ifndef __CUSTOM_MEMORYDEVICE__
#define __CUSTOM_MEMORYDEVICE__



#define BOARD_ID                MT6577_EVB

#define CS_PART_NUMBER[0]       KMNJS000ZM_B205
#define CS_PART_NUMBER[1]       KMKJS000VM_B309

#endif /* __CUSTOM_MEMORYDEVICE__ */
