
#if defined(X_DEF_CH)
#define CCCI_CH_X(a, b) a = b,
#endif  /* X_DEF_CH */

#if defined(X_DEF_CTRL)
#define CCCI_CH_X(a, b) __ATTR(a, 0644, NULL, NULL),
#endif  /* X_DEF_CTRL */

#if defined(X_DEF_ATTR)
#define CCCI_CH_X(a, b) &(ccci_ctrl[a].attr),
#endif  /* X_DEF_ATTR */

CCCI_CH_X(CCCI_CONTROL_RX, 0)
CCCI_CH_X(CCCI_CONTROL_TX, 1)
CCCI_CH_X(CCCI_SYSTEM_RX, 2)
CCCI_CH_X(CCCI_SYSTEM_TX, 3)
CCCI_CH_X(CCCI_PCM_RX, 4)
CCCI_CH_X(CCCI_PCM_TX, 5)
CCCI_CH_X(CCCI_UART1_RX, 6)
CCCI_CH_X(CCCI_UART1_RX_ACK, 7)
CCCI_CH_X(CCCI_UART1_TX, 8)
CCCI_CH_X(CCCI_UART1_TX_ACK, 9)
CCCI_CH_X(CCCI_UART2_RX, 10)
CCCI_CH_X(CCCI_UART2_RX_ACK, 11)
CCCI_CH_X(CCCI_UART2_TX, 12)
CCCI_CH_X(CCCI_UART2_TX_ACK, 13)
CCCI_CH_X(CCCI_FS_RX, 14)
CCCI_CH_X(CCCI_FS_TX, 15)
CCCI_CH_X(CCCI_PMIC_RX, 16)
CCCI_CH_X(CCCI_PMIC_TX, 17)
CCCI_CH_X(CCCI_UEM_RX, 18)
CCCI_CH_X(CCCI_UEM_TX, 19)

#undef CCCI_CH_X
